
/*
 *
 *    Copyright (c) 2018-2025 Green Button Alliance, Inc.
 *
 *    Portions (c) 2013-2018 EnergyOS.org
 *
 *     Licensed under the Apache License, Version 2.0 (the "License");
 *     you may not use this file except in compliance with the License.
 *     You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 *     Unless required by applicable law or agreed to in writing, software
 *     distributed under the License is distributed on an "AS IS" BASIS,
 *     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *     See the License for the specific language governing permissions and
 *     limitations under the License.
 *
 */

package org.greenbuttonalliance.espi.common.domain.usage;

import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;
import org.greenbuttonalliance.espi.common.domain.legacy.DateTimeInterval;
import org.greenbuttonalliance.espi.common.domain.common.IdentifiedObject;
import org.hibernate.annotations.LazyCollection;
import org.hibernate.annotations.LazyCollectionOption;

import jakarta.persistence.*;
import java.util.ArrayList;
import java.util.List;

/**
 * Pure JPA/Hibernate entity for IntervalBlock without JAXB concerns.
 *
 * Represents a time sequence of readings of the same ReadingType.
 * Contains a date/time interval and a collection of interval readings.
 */
@Entity
@Table(name = "interval_blocks", uniqueConstraints = {
    @UniqueConstraint(columnNames = {"uuid"})
})
@Data
@EqualsAndHashCode(callSuper = true)
@NoArgsConstructor
@ToString(callSuper = true, exclude = {"intervalReadings", "meterReading"})
public class IntervalBlockEntity extends IdentifiedObject {

    private static final long serialVersionUID = 1L;

    /**
     * Date and time interval for this block.
     * Embedded value object containing start time and duration.
     */
    @Embedded
    @AttributeOverrides({
        @AttributeOverride(name = "start", column = @Column(name = "interval_start")),
        @AttributeOverride(name = "duration", column = @Column(name = "interval_duration"))
    })
    private DateTimeInterval interval;

    /**
     * Meter reading that this interval block belongs to.
     * Many interval blocks can belong to one meter reading.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "meter_reading_id")
    private MeterReadingEntity meterReading;

    /**
     * Collection of interval readings within this block.
     * One-to-many relationship with cascade operations.
     * Uses eager loading for performance.
     */
    @OneToMany(mappedBy = "intervalBlock", cascade = CascadeType.ALL, orphanRemoval = true)
    @LazyCollection(LazyCollectionOption.FALSE)
    private List<IntervalReadingEntity> intervalReadings = new ArrayList<>();

    /**
     * Constructor with interval parameters.
     *
     * @param interval the date/time interval for this block
     */
    public IntervalBlockEntity(DateTimeInterval interval) {
        this.interval = interval;
    }

    // Note: Interval reading collection accessors are generated by Lombok @Data
    // Bidirectional relationship management methods removed - handled by DataCustodian/ThirdParty applications

    // Note: Simple setMeterReading setter is generated by Lombok @Data
    // Complex bidirectional relationship management removed - handled by DataCustodian/ThirdParty applications

    /**
     * Generates the self href for this interval block.
     *
     * @return self href string
     */
    public String getSelfHref() {
        if (meterReading != null) {
            return meterReading.getSelfHref() + "/IntervalBlock/" + getHashedId();
        }
        return "/espi/1_1/resource/IntervalBlock/" + getHashedId();
    }

    /**
     * Generates the up href for this interval block.
     *
     * @return up href string pointing to the meter reading
     */
    public String getUpHref() {
        if (meterReading != null) {
            return meterReading.getSelfHref() + "/IntervalBlock";
        }
        return "/espi/1_1/resource/IntervalBlock";
    }

    /**
     * Overrides the default self href generation to use interval block specific logic.
     *
     * @return self href for this interval block
     */
    @Override
    protected String generateDefaultSelfHref() {
        return getSelfHref();
    }

    /**
     * Overrides the default up href generation to use interval block specific logic.
     *
     * @return up href for this interval block
     */
    @Override
    protected String generateDefaultUpHref() {
        return getUpHref();
    }

    /**
     * Merges data from another IntervalBlockEntity.
     * Updates interval and replaces interval readings with bidirectional setup.
     *
     * @param other the other interval block entity to merge from
     */
    public void merge(IntervalBlockEntity other) {
        if (other != null) {
            super.merge(other);

            // Update interval
            this.interval = other.interval;

            // Replace interval readings - bidirectional relationship setup handled by applications
            if (other.intervalReadings != null) {
                this.intervalReadings = new ArrayList<>(other.intervalReadings);
            }

            // Update meter reading if provided
            if (other.meterReading != null) {
                this.meterReading = other.meterReading;
            }
        }
    }

    /**
     * Clears all relationships when unlinking the entity.
     * Simplified - applications handle relationship cleanup.
     */
    public void unlink() {
        clearRelatedLinks();

        // Simple collection clearing - applications handle bidirectional cleanup
        intervalReadings.clear();

        // Clear relationships with simple field assignment
        this.meterReading = null;
    }

    /**
     * Sets up the parent relationship with a meter reading.
     * Used by the resource management system.
     * Note: Bidirectional relationship setup handled by applications.
     *
     * @param resource the parent meter reading resource
     */
    public void setUpResource(IdentifiedObject resource) {
        if (resource instanceof MeterReadingEntity parentMeterReading) {
            this.meterReading = parentMeterReading;
        }
    }

    /**
     * Gets the query for finding parent resources.
     * Used by the resource management system.
     *
     * @return the parent query string
     */
    public String getParentQuery() {
        return "MeterReadingEntity.findByRelatedHref";
    }
}
