/*
 * Copyright 2013 EnergyOS.org
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.27 at 01:43:57 PM EDT 
//


package org.energyos.espi.common.domain;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.CollectionTable;
import javax.persistence.ElementCollection;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import org.energyos.espi.common.models.atom.adapters.ApplicationInformationAdapter;
import org.hibernate.annotations.LazyCollection;
import org.hibernate.annotations.LazyCollectionOption;
import org.hibernate.validator.constraints.NotEmpty;




/**
 * [extension] Contains information about a Third Party Application requesting access to the DataCustodian services. Information requested may include items such as Organization Name, Website, Contact Info, Application Name, Description, Icon, Type, default Notification and Callback endpoints, and may also include agreement with terms of service.
 * 
 * Atom Links:
 * self link to this resource
 * 
 * <p>Java class for ApplicationInformation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ApplicationInformation">
 *   &lt;complexContent>
 *     &lt;extension base="{http://naesb.org/espi}IdentifiedObject">
 *       &lt;sequence>
 *         &lt;element name="dataCustodianApplicationStatus" type="{http://naesb.org/espi}DataCustodianApplicationStatus" minOccurs="0"/>
 *         &lt;element name="dataCustodianDefaultBatchResource" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="dataCustodianDefaultSubscriptionResource" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="thirdPartyApplicationDescription" type="{http://naesb.org/espi}String256" minOccurs="0"/>
 *         &lt;element name="thirdPartyApplicationStatus" type="{http://naesb.org/espi}ThirdPartyApplicatonStatus" minOccurs="0"/>
 *         &lt;element name="thirdPartyApplicationType" type="{http://naesb.org/espi}ThirdPartyApplicationType" minOccurs="0"/>
 *         &lt;element name="thirdPartyApplicationUse" type="{http://naesb.org/espi}ThirdPartyApplicationUse" minOccurs="0"/>
 *         &lt;element name="thirdPartyPhone" type="{http://naesb.org/espi}String32" minOccurs="0"/>
 *         &lt;element name="authorizationServerUri" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="thirdPartyNotifyUri" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="authorizationServerAuthorizationEndpoint" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="authorizationServerRegistrationEndpoint" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="authorizationServerTokenEndpoint" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="dataCustodianBulkRequestURI" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="dataCustodianThirdPartySelectionScreenURI" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="dataCustodianResourceEndpoint" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="thirdPartyDataCustodianSelectionScreenURI" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="thirdPartyLoginScreenURI" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="thirdPartyScopeSelectionScreenURI" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="thirdPartyUserPortalScreenURI" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="client_secret" type="{http://naesb.org/espi}String512" minOccurs="0"/>
 *         &lt;element name="logo_uri" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="client_name" type="{http://naesb.org/espi}String256" minOccurs="0"/>
 *         &lt;element name="client_uri" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="redirect_uri" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="client_id" type="{http://naesb.org/espi}String32" minOccurs="0"/>
 *         &lt;element name="tos_uri" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="policy_uri" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="software_id" type="{http://naesb.org/espi}String32" minOccurs="0"/>
 *         &lt;element name="software_version" type="{http://naesb.org/espi}String32" minOccurs="0"/>
 *         &lt;element name="client_id_issued_at" type="{http://naesb.org/espi}TimeType" minOccurs="0"/>
 *         &lt;element name="client_secret_expires_at" type="{http://naesb.org/espi}TimeType" minOccurs="0"/>
 *         &lt;element name="contacts" type="{http://naesb.org/espi}String256" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="token_endpoint_auth_method" type="{http://naesb.org/espi}TokenEndPointMethod" minOccurs="0"/>
 *         &lt;element name="scope" type="{http://naesb.org/espi}String256" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="grant_types" type="{http://naesb.org/espi}GrantType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="response_types" type="{http://naesb.org/espi}ResponseType" minOccurs="0"/>
 *         &lt;element name="registration_client_uri" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="registration_access_token" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ApplicationInformation", propOrder = {
	    "dataCustodianApplicationStatus",
	    "dataCustodianDefaultBatchResource",
	    "dataCustodianDefaultSubscriptionResource",
	    "thirdPartyApplicationDescription",
	    "thirdPartyApplicationStatus",
	    "thirdPartyApplicationType",
	    "thirdPartyApplicationUse",
	    "thirdPartyPhone",
	    "authorizationServerUri",
	    "thirdPartyNotifyUri",
	    "authorizationServerAuthorizationEndpoint",
	    "authorizationServerRegistrationEndpoint",
	    "authorizationServerTokenEndpoint",
	    "dataCustodianBulkRequestURI",
	    "dataCustodianThirdPartySelectionScreenURI",
	    "dataCustodianResourceEndpoint",
	    "thirdPartyDataCustodianSelectionScreenURI",
	    "thirdPartyLoginScreenURI",
	    "thirdPartyScopeSelectionScreenURI",
	    "thirdPartyUserPortalScreenURI",
	    "clientSecret",
	    "logoUri",
	    "clientName",
	    "clientUri",
	    "redirectUri",
	    "clientId",
	    "tosUri",
	    "policyUri",
	    "softwareId",
	    "softwareVersion",
	    "clientIdIssuedAt",
	    "clientSecretExpiresAt",
	    "contacts",
	    "tokenEndpointAuthMethod",
	    "scope",
	    "grantTypes",
	    "responseTypes",
	    "registrationClientUri",
	    "registrationAccessToken",
	    "dataCustodianId",
	    "thirdPartyApplicationName"
	})
@Entity
@Table(name = "application_information")
@XmlJavaTypeAdapter(ApplicationInformationAdapter.class)
@NamedQueries(value = {
        @NamedQuery(name = ApplicationInformation.QUERY_FIND_BY_ID, query = "SELECT appinfo FROM ApplicationInformation appinfo WHERE appinfo.id = :id"),
        @NamedQuery(name = ApplicationInformation.QUERY_FIND_BY_UUID, query = "SELECT appinfo FROM ApplicationInformation appinfo WHERE appinfo.uuid = :uuid"),
        @NamedQuery(name = ApplicationInformation.QUERY_FIND_BY_CLIENT_ID, query = "SELECT info FROM ApplicationInformation info WHERE info.clientId = :clientId"),
        @NamedQuery(name = ApplicationInformation.QUERY_FIND_BY_DATA_CUSTODIAN_CLIENT_ID, query = "SELECT info FROM ApplicationInformation info WHERE info.dataCustodianId = :dataCustodianId"),
        @NamedQuery(name = ApplicationInformation.QUERY_FIND_ALL, query = "SELECT info FROM ApplicationInformation info"),
        @NamedQuery(name = ApplicationInformation.QUERY_FIND_ALL_IDS,
		    query = "SELECT applicationInformation.id FROM ApplicationInformation applicationInformation")

})
public class ApplicationInformation
        extends IdentifiedObject {
    /**
	 * 
	 */
	// private static final long serialVersionUID = 1L;
	public final static String QUERY_FIND_ALL = "ApplicationInformation.findAll";
	public final static String QUERY_FIND_BY_UUID = "ApplicationInformation.findByUUID";
    public static final String QUERY_FIND_BY_ID = "ApplicationInformation.findById";
    public static final String QUERY_FIND_BY_CLIENT_ID = "ApplicationInformation.findByClientId";
    public static final String QUERY_FIND_BY_DATA_CUSTODIAN_CLIENT_ID = "ApplicationInformation.findByDataCustodianClientId";
	public static final String QUERY_FIND_ALL_IDS = "AppilcationInformation.findAllIds";

    
    protected String dataCustodianApplicationStatus;
    @XmlSchemaType(name = "anyURI")
    protected String dataCustodianDefaultBatchResource;
    @XmlSchemaType(name = "anyURI")
    protected String dataCustodianDefaultSubscriptionResource;
    protected String thirdPartyApplicationDescription;
    protected String thirdPartyApplicationStatus;
    protected String thirdPartyApplicationType;
    protected String thirdPartyApplicationUse;
    protected String thirdPartyPhone;
    @XmlSchemaType(name = "anyURI")
    protected String authorizationServerUri;
    @XmlSchemaType(name = "anyURI")
    protected String thirdPartyNotifyUri;
    @XmlElement(name = "authorizationServerAuthorizationEndpoint")
    @XmlSchemaType(name = "anyURI")
    protected String authorizationServerAuthorizationEndpoint;
    @XmlElement(name = "authorizationServerRegistrationEndpoint")
    @XmlSchemaType(name = "anyURI")
    protected String authorizationServerRegistrationEndpoint;
    @XmlElement(name = "authorizationServerTokenEndpoint")
    @XmlSchemaType(name = "anyURI")
    protected String authorizationServerTokenEndpoint;
    @XmlElement(name = "dataCustodianBulkRequestURI")
    @XmlSchemaType(name = "anyURI")
    protected String dataCustodianBulkRequestURI;
    @XmlElement(name = "dataCustodianThirdPartySelectionScreenURI")
    @XmlSchemaType(name = "anyURI")
    protected String dataCustodianThirdPartySelectionScreenURI;
    @XmlElement(name = "dataCustodianResourceEndpoint")
    @XmlSchemaType(name = "anyURI")
    protected String dataCustodianResourceEndpoint;
    @XmlElement(name = "thirdPartyDataCustodianSelectionScreenURI")
    @XmlSchemaType(name = "anyURI")
    protected String thirdPartyDataCustodianSelectionScreenURI;
    @XmlElement(name = "thirdPartyLoginScreenURI")
    @XmlSchemaType(name = "anyURI")
    protected String thirdPartyLoginScreenURI;
    @XmlElement(name = "thirdPartyScopeSelectionScreenURI")
    @XmlSchemaType(name = "anyURI")
    protected String thirdPartyScopeSelectionScreenURI;
    @XmlElement(name = "thirdPartyUserPortalScreenURI")
    @XmlSchemaType(name = "anyURI")
    protected String thirdPartyUserPortalScreenURI;
    @XmlElement(name = "client_secret")
    protected String clientSecret;
    @XmlElement(name = "logo_uri")
    @XmlSchemaType(name = "anyURI")
    protected String logoUri;
    @XmlElement(name = "client_name")
    protected String clientName;
    @XmlElement(name = "client_uri")
    @XmlSchemaType(name = "anyURI")
    protected String clientUri;
    @XmlElement(name = "redirect_uri")
    @XmlSchemaType(name = "anyURI")
    protected String redirectUri;
    @NotEmpty
    @Size(min = 2, max = 64)
    @XmlElement(name = "client_id")
    protected String clientId;
    @XmlElement(name = "tos_uri")
    @XmlSchemaType(name = "anyURI")
    protected String tosUri;
    @XmlElement(name = "policy_uri")
    @XmlSchemaType(name = "anyURI")
    protected String policyUri;
    @XmlElement(name = "software_id")
    protected String softwareId;
    @XmlElement(name = "software_version")
    protected String softwareVersion;
    @XmlElement(name = "client_id_issued_at")
    protected Long clientIdIssuedAt;
    @XmlElement(name = "client_secret_expires_at")
    protected Long clientSecretExpiresAt;
    protected ArrayList<String> contacts;
    @XmlElement(name = "token_endpoint_auth_method")
    protected String tokenEndpointAuthMethod;
    
    // TODO Implement ApplicationInformaion.additionalInformation
    
    //@XmlElement(name = "additional_information")
    //Map<String, java.lang.Object> additionalInformation = null; 
    
 //   @XmlTransient
    @ElementCollection
    @LazyCollection(LazyCollectionOption.FALSE)
    @CollectionTable(name="application_information_scopes", joinColumns=@JoinColumn(name="application_information_id"))
    private Set<String> scope = new HashSet<>();   
    
    @XmlElement(name = "grant_types")
    protected ArrayList<GrantType> grantTypes;
    
    @XmlElement(name = "response_types")
    protected ResponseType responseTypes;
    
    @XmlElement(name = "registration_client_uri")
    @XmlSchemaType(name = "anyURI")
    protected String registrationClientUri;
    
    @XmlElement(name = "registration_access_token")
    protected String registrationAccessToken;

    
    @Size(min = 2, max = 64)
    @XmlElement(name = "dataCustodianId")
	protected String dataCustodianId;
    
    @NotEmpty
    @Size(min = 2, max = 64)
    @XmlElement(name = "thirdPartyApplicationName")
    protected String thirdPartyApplicationName;
    
	// private Integer accessTokenValiditySeconds;
	// TODO implement ApplicationInformation.authorities
	// private Collection<GrantedAuthority> authorities;

//    @Override
    public String getClientId() {
        return clientId;
    }

//    @Override
//    public Set<String> getResourceIds() {
//        return null;
//    }

//    public void setResourceIds(Set<String> ids) {
//    	// TODO seems not to be implemented??
//	    //this.resourceIds = ids;
//    }


//    @Override
//    public boolean isSecretRequired() {
//        return true;
//    }

//        @Override
//        public Set<String> getAuthorizedGrantTypes() {
//            Set<String> grantTypes = new HashSet<>();
//            grantTypes.add("authorization_code");
//            return grantTypes;
//        }

//        public void setAuthorizedGrantTypes (Set<String>  authorizedGrantTypes) {
//            // TODO seems not to be implemented ??                                                                                                                              
//            // this.grantTypes = authorizedGrantTypes; 
//        }


//    @Override
    public String getClientSecret() {
        return clientSecret;
    }

//    @Override
//    public boolean isScoped() {
//        return true;
//    }


//    @Override
    public Set<String> getScope() {
        return scope;
    }

    public void setScope(Set<String> scope) {
    	this.scope = scope;
    }
    
    public String[] getScopeArray() {
    	if (scope == null)
    		return new String[] {};
        return scope.toArray(new String[scope.size()]);
    }

//    @Override
//    public Set<String> getAuthorizedGrantTypes() {
//    	Set<String> grantTypes = new HashSet<>();
//    	grantTypes.add("authorization_code");
//    	return grantTypes;
//    }

//    public void setAuthorizedGrantTypes (Set<String> authorizedGrantTypes) {
//    	// TODO seems not to be implemented ??
//    	// this.grantTypes = authorizedGrantTypes;
//    }

//    @Override
//    public Set<String> getRegisteredRedirectUri() {
//    	Set<String> uris = new HashSet<>();
//    	uris.add(getRedirectUri());
//    	return uris;
//    }

//    public void setRegisteredRedirectUri(Set<String> registeredRediredUri) {
//    	this.redirectUri = registeredRediredUri.toString();
//    }

//    @Override
//    public Collection<GrantedAuthority> getAuthorities() {
//    	Collection<GrantedAuthority> authorities = new ArrayList<>();
//    	authorities.add(new SimpleGrantedAuthority("ROLE_CLIENT"));
//    	return authorities;
//    }

//    public void setAuthorities (Collection<GrantedAuthority> authorities) {
//    	// TODO this seems not to be implemented ??
//    	// this.authorities = authorities;
//    }
        
//    @Override
//    public Integer getAccessTokenValiditySeconds() {
//    	return Integer.valueOf(60*60*24*60);
//    }

//    public void setAccessTokenValiditySeconds(Integer s) {   	
//    	// TODO This seems not to be implemented ??
//    	// this.accessTokenValiditySeconds = s
//    }
        
//    @Override
//    public Integer getRefreshTokenValiditySeconds() {
//    	return Integer.valueOf(60*60*24);
//    }

//    public void setRefreshTokenValiditySeconds(Integer s) {
//    	// TODO This seems not to be implemented ??
//    	// this.accessTokenValiditySeconds = s
//    }
        
//    @Override
//    public Map<String, java.lang.Object> getAdditionalInformation() {
//    	return null;
//    }   
   
//    public void setAdditionalInformation(Map<String, java.lang.Object> map) {
//    	// TODO This seems not to be implemented ??
//    	// this.additionalInformation = additionalInformation;
//    }

//    public void setAuthorities (Collection<GrantedAuthority> authorities) {

        // TODO this seems not to be implemented ??                                                                                                                                  
         // this.authorities = authorities; 
//    } 
    
//        @Override
//        public Integer getAccessTokenValiditySeconds() {
//            return Integer.valueOf(60*60*24*60);
//        }

//        public void setAccessTokenValiditySeconds(Integer s) {   	
//            // TODO This seems not to be implemented ??                                                                                                                                
//            // this.accessTokenValiditySeconds = s  
//        }
        

//       @Override
//        public Integer getRefreshTokenValiditySeconds() {
//            return Integer.valueOf(60*60*24);
//        }

//        public void setRefreshTokenValiditySeconds(Integer s) {
//            // TODO This seems not to be implemented ??                                                                                                                             
//            // this.accessTokenValiditySeconds = s    
//        }
        
//        @Override
//        public Map<String, java.lang.Object> getAdditionalInformation() {
//           // TODO Implement ApplicationInformaion.additionalInformation
//           //  return this.additionalInformation;
//        	return null;
//        }   
   
//	public void setAdditionalInformation(Map<String, java.lang.Object> additionalInformation) {
//       // TODO This seems not to be implemented ??                                                                                                                                 
//       // this.additionalInformation = additionalInformation; 
//	}

    /**
     * Gets the value of the dataCustodianApplicationStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataCustodianApplicationStatus() {
        return dataCustodianApplicationStatus;
    }

    /**
     * Sets the value of the dataCustodianApplicationStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataCustodianApplicationStatus(String value) {
        this.dataCustodianApplicationStatus = value;
    }

    /**
     * Gets the value of the dataCustodianDefaultBatchResource property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataCustodianDefaultBatchResource() {
        return dataCustodianDefaultBatchResource;
    }

    /**
     * Sets the value of the dataCustodianDefaultBatchResource property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataCustodianDefaultBatchResource(String value) {
        this.dataCustodianDefaultBatchResource = value;
    }

    /**
     * Gets the value of the dataCustodianDefaultSubscriptionResource property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataCustodianDefaultSubscriptionResource() {
        return dataCustodianDefaultSubscriptionResource;
    }

    /**
     * Sets the value of the dataCustodianDefaultSubscriptionResource property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataCustodianDefaultSubscriptionResource(String value) {
        this.dataCustodianDefaultSubscriptionResource = value;
    }

    /**
     * Gets the value of the thirdPartyApplicationDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getThirdPartyApplicationDescription() {
        return thirdPartyApplicationDescription;
    }

    /**
     * Sets the value of the thirdPartyApplicationDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setThirdPartyApplicationDescription(String value) {
        this.thirdPartyApplicationDescription = value;
    }

    /**
     * Gets the value of the thirdPartyApplicationStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getThirdPartyApplicationStatus() {
        return thirdPartyApplicationStatus;
    }

    /**
     * Sets the value of the thirdPartyApplicationStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setThirdPartyApplicationStatus(String value) {
        this.thirdPartyApplicationStatus = value;
    }

    /**
     * Gets the value of the thirdPartyApplicationType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getThirdPartyApplicationType() {
        return thirdPartyApplicationType;
    }

    /**
     * Sets the value of the thirdPartyApplicationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setThirdPartyApplicationType(String value) {
        this.thirdPartyApplicationType = value;
    }

    /**
     * Gets the value of the thirdPartyApplicationUse property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getThirdPartyApplicationUse() {
        return thirdPartyApplicationUse;
    }

    /**
     * Sets the value of the thirdPartyApplicationUse property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setThirdPartyApplicationUse(String value) {
        this.thirdPartyApplicationUse = value;
    }

    /**
     * Gets the value of the thirdPartyPhone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getThirdPartyPhone() {
        return thirdPartyPhone;
    }

    /**
     * Sets the value of the thirdPartyPhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setThirdPartyPhone(String value) {
        this.thirdPartyPhone = value;
    }

    /**
     * Gets the value of the authorizationServerUri property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthorizationServerUri() {
        return authorizationServerUri;
    }

    /**
     * Sets the value of the authorizationServerUri property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthorizationServerUri(String value) {
        this.authorizationServerUri = value;
    }

    /**
     * Gets the value of the thirdPartyNotifyUri property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getThirdPartyNotifyUri() {
        return thirdPartyNotifyUri;
    }

    /**
     * Sets the value of the thirdPartyNotifyUri property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setThirdPartyNotifyUri(String value) {
        this.thirdPartyNotifyUri = value;
    }

    /**
     * Gets the value of the authorizationServerAuthorizationEndpoint property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthorizationServerAuthorizationEndpoint() {
        return authorizationServerAuthorizationEndpoint;
    }

    /**
     * Sets the value of the authorizationServerAuthorizationEndpoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthorizationServerAuthorizationEndpoint(String value) {
        this.authorizationServerAuthorizationEndpoint = value;
    }

    /**
     * Gets the value of the authorizationServerRegistrationEndpoint property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthorizationServerRegistrationEndpoint() {
        return authorizationServerRegistrationEndpoint;
    }

    /**
     * Sets the value of the authorizationServerRegistrationEndpoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthorizationServerRegistrationEndpoint(String value) {
        this.authorizationServerRegistrationEndpoint = value;
    }

    /**
     * Gets the value of the authorizationServerTokenEndpoint property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthorizationServerTokenEndpoint() {
        return authorizationServerTokenEndpoint;
    }

    /**
     * Sets the value of the authorizationServerTokenEndpoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthorizationServerTokenEndpoint(String value) {
        this.authorizationServerTokenEndpoint = value;
    }

    /**
     * Gets the value of the dataCustodianBulkRequestURI property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataCustodianBulkRequestURI() {
        return dataCustodianBulkRequestURI;
    }

    /**
     * Sets the value of the dataCustodianBulkRequestURI property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataCustodianBulkRequestURI(String value) {
        this.dataCustodianBulkRequestURI = value;
    }

    /**
     * Gets the value of the dataCustodianThirdPartySelectionScreenURI property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataCustodianThirdPartySelectionScreenURI() {
        return dataCustodianThirdPartySelectionScreenURI;
    }

    /**
     * Sets the value of the dataCustodianThirdPartySelectionScreenURI property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataCustodianThirdPartySelectionScreenURI(String value) {
        this.dataCustodianThirdPartySelectionScreenURI = value;
    }

    /**
     * Gets the value of the dataCustodianResourceEndpoint property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataCustodianResourceEndpoint() {
        return dataCustodianResourceEndpoint;
    }

    /**
     * Sets the value of the dataCustodianResourceEndpoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataCustodianResourceEndpoint(String value) {
        this.dataCustodianResourceEndpoint = value;
    }

    /**
     * Gets the value of the thirdPartyDataCustodianSelectionScreenURI property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getThirdPartyDataCustodianSelectionScreenURI() {
        return thirdPartyDataCustodianSelectionScreenURI;
    }

    /**
     * Sets the value of the thirdPartyDataCustodianSelectionScreenURI property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setThirdPartyDataCustodianSelectionScreenURI(String value) {
        this.thirdPartyDataCustodianSelectionScreenURI = value;
    }

    /**
     * Gets the value of the thirdPartyLoginScreenURI property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getThirdPartyLoginScreenURI() {
        return thirdPartyLoginScreenURI;
    }

    /**
     * Sets the value of the thirdPartyLoginScreenURI property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setThirdPartyLoginScreenURI(String value) {
        this.thirdPartyLoginScreenURI = value;
    }

    /**
     * Gets the value of the thirdPartyScopeSelectionScreenURI property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getThirdPartyScopeSelectionScreenURI() {
        return thirdPartyScopeSelectionScreenURI;
    }

    /**
     * Sets the value of the thirdPartyScopeSelectionScreenURI property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setThirdPartyScopeSelectionScreenURI(String value) {
        this.thirdPartyScopeSelectionScreenURI = value;
    }

    /**
     * Gets the value of the thirdPartyUserPortalScreenURI property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getThirdPartyUserPortalScreenURI() {
        return thirdPartyUserPortalScreenURI;
    }

    /**
     * Sets the value of the thirdPartyUserPortalScreenURI property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setThirdPartyUserPortalScreenURI(String value) {
        this.thirdPartyUserPortalScreenURI = value;
    }

    /**
     * Sets the value of the clientSecret property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClientSecret(String value) {
        this.clientSecret = value;
    }

    /**
     * Gets the value of the logoUri property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLogoUri() {
        return logoUri;
    }

    /**
     * Sets the value of the logoUri property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLogoUri(String value) {
        this.logoUri = value;
    }

    /**
     * Gets the value of the clientName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClientName() {
        return clientName;
    }

    /**
     * Sets the value of the clientName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClientName(String value) {
        this.clientName = value;
    }

    /**
     * Gets the value of the clientUri property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClientUri() {
        return clientUri;
    }

    /**
     * Sets the value of the clientUri property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClientUri(String value) {
        this.clientUri = value;
    }

    /**
     * Gets the value of the redirectUri property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRedirectUri() {
        return redirectUri;
    }

    /**
     * Sets the value of the redirectUri property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRedirectUri(String value) {
        this.redirectUri = value;
    }

    /**
     * Sets the value of the clientId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClientId(String value) {
        this.clientId = value;
    }

    /**
     * Gets the value of the tosUri property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTosUri() {
        return tosUri;
    }

    /**
     * Sets the value of the tosUri property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTosUri(String value) {
        this.tosUri = value;
    }

    /**
     * Gets the value of the policyUri property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPolicyUri() {
        return policyUri;
    }

    /**
     * Sets the value of the policyUri property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPolicyUri(String value) {
        this.policyUri = value;
    }

    /**
     * Gets the value of the softwareId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSoftwareId() {
        return softwareId;
    }

    /**
     * Sets the value of the softwareId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSoftwareId(String value) {
        this.softwareId = value;
    }

    /**
     * Gets the value of the softwareVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSoftwareVersion() {
        return softwareVersion;
    }

    /**
     * Sets the value of the softwareVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSoftwareVersion(String value) {
        this.softwareVersion = value;
    }

    /**
     * Gets the value of the clientIdIssuedAt property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getClientIdIssuedAt() {
        return clientIdIssuedAt;
    }

    /**
     * Sets the value of the clientIdIssuedAt property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setClientIdIssuedAt(Long value) {
        this.clientIdIssuedAt = value;
    }

    /**
     * Gets the value of the clientSecretExpiresAt property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getClientSecretExpiresAt() {
        return clientSecretExpiresAt;
    }

    /**
     * Sets the value of the clientSecretExpiresAt property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setClientSecretExpiresAt(Long value) {
        this.clientSecretExpiresAt = value;
    }

    /**
     * Gets the value of the contacts property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the contacts property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContacts().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getContacts() {
        if (contacts == null) {
            contacts = new ArrayList<String>();
        }
        return this.contacts;
    }

    public void setContacts(List<String> contacts) {
	this.contacts = (ArrayList<String>) contacts;
    }

    /**
     * Gets the value of the tokenEndpointAuthMethod property.
     * 
     * @return
     *     possible object is
     *     {@link TokenEndPointMethod }
     *     
     */
    public String getTokenEndpointAuthMethod() {
        return tokenEndpointAuthMethod;
    }

    /**
     * Sets the value of the tokenEndpointAuthMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link TokenEndPointMethod }
     *     
     */
    public void setTokenEndpointAuthMethod(String value) {
        this.tokenEndpointAuthMethod = value;
    }


    /**
     * Gets the value of the grantTypes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the grantTypes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGrantTypes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GrantType }
     * 
     * 
     */
    public List<GrantType> getGrantTypes() {
        if (grantTypes == null) {
            grantTypes = new ArrayList<GrantType>();
        }
        return this.grantTypes;
    }


        private void setGrantTypes(List<GrantType> grantTypes) {
                this.grantTypes = (ArrayList<GrantType>) grantTypes;

        }
	
    /**
     * Gets the value of the responseTypes property.
     * 
     * @return
     *     possible object is
     *     {@link ResponseType }
     *     
     */
    public ResponseType getResponseTypes() {
        return responseTypes;
    }

    /**
     * Sets the value of the responseTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResponseType }
     *     
     */
    public void setResponseTypes(ResponseType value) {
        this.responseTypes = value;
    }

    /**
     * Gets the value of the registrationClientUri property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegistrationClientUri() {
        return registrationClientUri;
    }

    /**
     * Sets the value of the registrationClientUri property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegistrationClientUri(String value) {
        this.registrationClientUri = value;
    }

    /**
     * Gets the value of the registrationAccessToken property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.Object }
     *     
     */
    public java.lang.Object getRegistrationAccessToken() {
        return registrationAccessToken;
    }

    private void setRegistrationAccessToken(java.lang.Object registrationAccessToken) {
	    this.registrationAccessToken = registrationAccessToken.toString();
    }
   

    /**
     * Sets the value of the registrationAccessToken property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.Object }
     *     
     */
    public void setRegistrationAccessToken(String value) {
        this.registrationAccessToken = value;
    }
    
    /**
     * Gets the value of the thirdPartyApplicationName property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getThirdPartyApplicationName() {
        return thirdPartyApplicationName;
    }

    /**
     * Sets the value of the thirdPartyApplicationName property.
     *
     * @param value allowed object is
     * {@link String }
     */
    public void setThirdPartyApplicationName(String value) {
        this.thirdPartyApplicationName = value;
    }

    /**
     * Gets the value of the thirdPartyApplicationName property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getDataCustodianId() {
        return dataCustodianId;
    }

    /**
     * Sets the value of the thirdPartyApplicationName property.
     *
     * @param value allowed object is
     * {@link String }
     */
    public void setDataCustodianId(String value) {
        this.dataCustodianId = value;
    }

      
	@Override
    public void merge(IdentifiedObject resource) {
    	super.merge(resource);
    	this.setDataCustodianId(((ApplicationInformation)resource).getDataCustodianId());
    	this.setClientId(((ApplicationInformation)resource).getClientId());
//    	this.setResourceIds(((ApplicationInformation)resource).getResourceIds());
    	this.setClientSecret(((ApplicationInformation)resource).getClientSecret());
    	this.setScope(((ApplicationInformation)resource).getScope());
//    	this.setAuthorizedGrantTypes(((ApplicationInformation)resource).getAuthorizedGrantTypes());
    	this.setGrantTypes(((ApplicationInformation)resource).getGrantTypes());
//    	this.setRegisteredRedirectUri(((ApplicationInformation)resource).getRegisteredRedirectUri());
    	this.setRedirectUri(((ApplicationInformation)resource).getRedirectUri());
//    	this.setAuthorities(((ApplicationInformation)resource).getAuthorities());
//    	this.setAccessTokenValiditySeconds(((ApplicationInformation)resource).getAccessTokenValiditySeconds());
//    	this.setRefreshTokenValiditySeconds(((ApplicationInformation)resource).getRefreshTokenValiditySeconds());
//    	this.setAdditionalInformation(((ApplicationInformation)resource).getAdditionalInformation());
    	this.setDataCustodianApplicationStatus(((ApplicationInformation)resource).getDataCustodianApplicationStatus());
    	this.setDataCustodianDefaultBatchResource(((ApplicationInformation)resource).getDataCustodianDefaultBatchResource());
    	this.setDataCustodianDefaultSubscriptionResource(((ApplicationInformation)resource).getDataCustodianDefaultSubscriptionResource());
    	this.setThirdPartyApplicationDescription(((ApplicationInformation)resource).getThirdPartyApplicationDescription());
    	this.setThirdPartyApplicationStatus(((ApplicationInformation)resource).getThirdPartyApplicationStatus());
    	this.setThirdPartyApplicationType(((ApplicationInformation)resource).getThirdPartyApplicationType());
    	this.setThirdPartyApplicationUse(((ApplicationInformation)resource).getThirdPartyApplicationUse());
    	this.setThirdPartyPhone(((ApplicationInformation)resource).getThirdPartyPhone());
    	this.setAuthorizationServerUri(((ApplicationInformation)resource).getAuthorizationServerUri());
    	this.setThirdPartyNotifyUri(((ApplicationInformation)resource).getThirdPartyNotifyUri());
    	this.setAuthorizationServerAuthorizationEndpoint(((ApplicationInformation)resource).getAuthorizationServerAuthorizationEndpoint());
    	this.setAuthorizationServerRegistrationEndpoint(((ApplicationInformation)resource).getAuthorizationServerRegistrationEndpoint());
    	this.setAuthorizationServerTokenEndpoint(((ApplicationInformation)resource).getAuthorizationServerTokenEndpoint());
    	this.setDataCustodianBulkRequestURI(((ApplicationInformation)resource).getDataCustodianBulkRequestURI());
    	this.setDataCustodianThirdPartySelectionScreenURI(((ApplicationInformation)resource).getDataCustodianThirdPartySelectionScreenURI());
    	this.setDataCustodianResourceEndpoint(((ApplicationInformation)resource).getDataCustodianResourceEndpoint());
    	this.setThirdPartyDataCustodianSelectionScreenURI(((ApplicationInformation)resource).getThirdPartyDataCustodianSelectionScreenURI());
    	this.setThirdPartyLoginScreenURI(((ApplicationInformation)resource).getThirdPartyLoginScreenURI());
    	this.setThirdPartyScopeSelectionScreenURI(((ApplicationInformation)resource).getThirdPartyScopeSelectionScreenURI());
    	this.setThirdPartyUserPortalScreenURI(((ApplicationInformation)resource).getThirdPartyUserPortalScreenURI());
    	this.setLogoUri(((ApplicationInformation)resource).getLogoUri());
    	this.setClientName(((ApplicationInformation)resource).getClientName());
    	this.setClientUri(((ApplicationInformation)resource).getClientUri());
    	this.setRedirectUri(((ApplicationInformation)resource).getRedirectUri());
    	this.setTosUri(((ApplicationInformation)resource).getTosUri());
    	this.setPolicyUri(((ApplicationInformation)resource).getPolicyUri());
    	this.setSoftwareId(((ApplicationInformation)resource).getSoftwareId());
    	this.setSoftwareVersion(((ApplicationInformation)resource).getSoftwareVersion());
    	this.setClientIdIssuedAt(((ApplicationInformation)resource).getClientIdIssuedAt());
    	this.setClientSecretExpiresAt(((ApplicationInformation)resource).getClientSecretExpiresAt());
    	this.setContacts(((ApplicationInformation)resource).getContacts());
    	this.setTokenEndpointAuthMethod(((ApplicationInformation)resource).getTokenEndpointAuthMethod());
    	this.setGrantTypes(((ApplicationInformation)resource).getGrantTypes());
    	this.setResponseTypes(((ApplicationInformation)resource).getResponseTypes());
    	this.setRegistrationClientUri(((ApplicationInformation)resource).getRegistrationClientUri());
    	this.setRegistrationAccessToken(((ApplicationInformation)resource).getRegistrationAccessToken());
    	this.setThirdPartyApplicationName(((ApplicationInformation)resource).getThirdPartyApplicationName());
    }
   
}
