/*
 * Copyright 2013 EnergyOS.org
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.08.27 at 01:43:57 PM EDT
//


package org.energyos.espi.common.domain;

import javax.persistence.Embeddable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * Interval of date and time. End is not included because it can be derived from the start and the duration.
 * <p/>
 * <p>Java class for DateTimeInterval complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="DateTimeInterval">
 *   &lt;complexContent>
 *     &lt;extension base="{http://naesb.org/espi}Object">
 *       &lt;sequence>
 *         &lt;element name="duration" type="{http://naesb.org/espi}UInt32" minOccurs="0"/>
 *         &lt;element name="start" type="{http://naesb.org/espi}TimeType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DateTimeInterval", propOrder = {
        "duration",
        "start"
})
@Embeddable
public class DateTimeInterval
        extends Object {

    protected Long duration;
    protected Long start;

    public DateTimeInterval() {
    }

    public DateTimeInterval(Long duration, Long start) {
        this.duration = duration;
        this.start = start;
    }

    /**
     * Gets the value of the duration property.
     *
     * @return possible object is
     *         {@link Long }
     */
    public Long getDuration() {
        return duration;
    }

    /**
     * Sets the value of the duration property.
     *
     * @param value allowed object is
     * {@link Long }
     */
    public void setDuration(Long value) {
        this.duration = value;
    }

    /**
     * Gets the value of the start property.
     *
     * @return possible object is
     *         {@link Long }
     */
    public Long getStart() {
        return start;
    }

    /**
     * Sets the value of the start property.
     *
     * @param value allowed object is
     * {@link Long }
     */
    public void setStart(Long value) {
        this.start = value;
    }

}
