# Spring Boot 3.5 Local Development Profile - H2 In-Memory Database
# Copyright (c) 2018-2025 Green Button Alliance, Inc.

spring:
  profiles:
    active: local
  
  # H2 In-Memory Database Configuration
  datasource:
    url: jdbc:h2:mem:openespi_local;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MySQL
    username: sa
    password: ""
    driver-class-name: org.h2.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 300000
      max-lifetime: 1200000

  # H2 Console Configuration
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
        trace: false

  # JPA/Hibernate Configuration
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 20
        hbm2ddl:
          import_files: db/data/local-sample-data.sql
        connection:
          provider_disables_autocommit: true
        cache:
          use_second_level_cache: false
          use_query_cache: false
    show-sql: true
    open-in-view: false

  # Flyway Configuration (disabled for H2 create-drop)
  flyway:
    enabled: false

  # Jackson Configuration
  jackson:
    default-property-inclusion: non_null
    serialization:
      write_dates_as_timestamps: false
      indent_output: true
    deserialization:
      fail_on_unknown_properties: false

# Logging Configuration for Local Development
logging:
  level:
    org.greenbuttonalliance.espi: DEBUG
    org.springframework: INFO
    org.hibernate: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    org.springframework.transaction: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# Management - Basic configuration (applications should extend)
management:
  endpoints:
    enabled-by-default: false
  info:
    env:
      enabled: true

# ESPI Configuration for Local Development
espi:
  database:
    usage-schema: PUBLIC
    customer-schema: PUBLIC
  security:
    oauth2:
      debug: true
      mock-enabled: true
  features:
    debug-mode: true
    sql-logging: true
    sample-data: true

# Local Development Server Configuration
server:
  port: 8080
  error:
    include-stacktrace: always
    include-message: always
    include-binding-errors: always