# Spring Boot 3.5 Docker Profile - Containerized Environment
# Copyright (c) 2018-2025 Green Button Alliance, Inc.

spring:
  profiles:
    active: docker
  
  # Database Configuration for Docker Compose
  datasource:
    url: ${DB_URL:jdbc:mysql://mysql:3306/openespi_docker}
    username: ${DB_USERNAME:openespi}
    password: ${DB_PASSWORD:openespi_password}
    driver-class-name: ${DB_DRIVER:com.mysql.cj.jdbc.Driver}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1200000
      connection-timeout: 30000
      validation-timeout: 5000
      leak-detection-threshold: 60000

  # JPA/Hibernate Configuration
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: false
        format_sql: true
        use_sql_comments: false
        jdbc:
          batch_size: 25
        connection:
          provider_disables_autocommit: true
        cache:
          use_second_level_cache: false
          use_query_cache: false
    show-sql: false
    open-in-view: false

  # Flyway Configuration for Docker
  flyway:
    enabled: true
    locations: classpath:db/migration/mysql
    baseline-on-migrate: true
    baseline-version: 1
    validate-on-migrate: true
    clean-disabled: true
    schemas:
      - openespi_usage
      - openespi_customer

  # Jackson Configuration
  jackson:
    default-property-inclusion: non_null
    serialization:
      write_dates_as_timestamps: false
      indent_output: false
    deserialization:
      fail_on_unknown_properties: false

# Logging Configuration for Docker
logging:
  level:
    org.greenbuttonalliance.espi: ${LOG_LEVEL_ESPI:INFO}
    org.springframework: ${LOG_LEVEL_SPRING:INFO}
    org.hibernate: ${LOG_LEVEL_HIBERNATE:WARN}
    org.hibernate.SQL: ${LOG_LEVEL_SQL:WARN}
    org.springframework.transaction: ${LOG_LEVEL_TRANSACTION:INFO}
    org.flywaydb: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# Management - Basic configuration (applications should configure endpoints)
management:
  endpoints:
    enabled-by-default: false
  info:
    env:
      enabled: true

# ESPI Configuration for Docker
espi:
  database:
    usage-schema: openespi_usage
    customer-schema: openespi_customer
  security:
    oauth2:
      debug: false
  features:
    debug-mode: false
    sql-logging: false

# Docker Server Configuration
server:
  port: 8080
  error:
    include-stacktrace: on_param
    include-message: always