# Spring Boot 3.5 Development Profile - PostgreSQL Database
# Copyright (c) 2018-2025 Green Button Alliance, Inc.

spring:
  profiles:
    active: dev-postgresql
  
  # PostgreSQL Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/openespi_dev?currentSchema=public
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1200000
      connection-timeout: 20000
      validation-timeout: 5000
      leak-detection-threshold: 60000

  # JPA/Hibernate Configuration
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: false
        format_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 25
          lob:
            non_contextual_creation: true
        connection:
          provider_disables_autocommit: true
        cache:
          use_second_level_cache: false
          use_query_cache: false
    show-sql: false
    open-in-view: false

  # Flyway Configuration for PostgreSQL
  flyway:
    enabled: true
    locations: classpath:db/migration/postgresql
    baseline-on-migrate: true
    baseline-version: 1
    validate-on-migrate: true
    clean-disabled: true
    schemas:
      - openespi_usage
      - openespi_customer

  # Jackson Configuration
  jackson:
    default-property-inclusion: non_null
    serialization:
      write_dates_as_timestamps: false
      indent_output: true
    deserialization:
      fail_on_unknown_properties: false

# Logging Configuration for Development
logging:
  level:
    org.greenbuttonalliance.espi: DEBUG
    org.springframework: INFO
    org.hibernate: WARN
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    org.springframework.transaction: DEBUG
    org.flywaydb: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"
  file:
    name: logs/openespi-dev-postgresql.log

# Management - Basic configuration (applications should extend)
management:
  endpoints:
    enabled-by-default: false
  info:
    env:
      enabled: true

# ESPI Configuration for Development
espi:
  database:
    usage-schema: openespi_usage
    customer-schema: openespi_customer
  security:
    oauth2:
      debug: true
  features:
    debug-mode: true
    sql-logging: true

# Development-specific settings
server:
  port: 8080
  error:
    include-stacktrace: always
    include-message: always