/* Add application_information */ 
INSERT INTO application_information (id, kind, description, published, self_link_href, self_link_rel, up_link_href, up_link_rel, updated, uuid, authorizationServerAuthorizationEndpoint, authorizationServerRegistrationEndpoint, authorizationServerTokenEndpoint, authorizationServerUri, clientId, clientIdIssuedAt , clientName, clientSecret, clientSecretExpiresAt, clientUri, contacts, dataCustodianApplicationStatus, dataCustodianBulkRequestURI, dataCustodianDefaultBatchResource, dataCustodianDefaultSubscriptionResource, dataCustodianId, dataCustodianResourceEndpoint, dataCustodianThirdPartySelectionScreenURI, grantTypes, logoUri, policyUri, redirectUri, registrationAccessToken, registrationClientUri, responseTypes, softwareId, softwareVersion, thirdPartyApplicationDescription, thirdPartyApplicationName, thirdPartyApplicationStatus, thirdPartyApplicationType, thirdPartyApplicationUse, thirdPartyDataCustodianSelectionScreenURI, thirdPartyLoginScreenURI, thirdPartyNotifyUri, thirdPartyPhone, thirdPartyScopeSelectionScreenURI, thirdPartyUserPortalScreenURI, tokenEndpointAuthMethod, tosUri, dataCustodianScopeSelectionScreenURI) 
VALUES (1,'THIRD_PARTY','GreenButtonData.org  ThirdParty Application','2014-01-02 05:00:00','/espi/1_1/resource/DataCustodian/ApplicationInformation/1','self','/espi/1_1/resource/DataCustodian/ApplicationInformation','up','2014-01-02 05:00:00','AF6E8B03-0299-467E-972A-A883ECDCC575','https://services.greenbuttondata.org/DataCustodian/oauth/authorize',NULL,'https://services.greenbuttondata.org/DataCustodian/oauth/token',NULL,'third_party',NULL,NULL,'secret',NULL,NULL,NULL,'1','',NULL,NULL,'data_custodian','https://services.greenbuttondata.org/DataCustodian/espi/1_1/resource',NULL,'authorization_code,refresh_token',NULL,NULL,'https://services.greenbuttondata.org/ThirdParty/espi/1_1/OAuthCallBack',NULL,NULL,NULL,NULL,NULL,NULL,'Third Party (localhost)',NULL,NULL,NULL,NULL,NULL,'https://services.greenbuttondata.orgThirdParty/espi/1_1/Notification',NULL,'https://services.greenbuttondata.orgThirdParty/RetailCustomer/ScopeSelection',NULL,'client_secret_basic',NULL,'https://services.greenbuttondata.org/DataCustodian/RetailCustomer/ScopeSelectionList');
INSERT INTO application_information (id, kind, description, published, self_link_href, self_link_rel, up_link_href, up_link_rel, updated, uuid, authorizationServerAuthorizationEndpoint, authorizationServerRegistrationEndpoint, authorizationServerTokenEndpoint, authorizationServerUri, clientId, clientIdIssuedAt , clientName, clientSecret, clientSecretExpiresAt, clientUri, contacts, dataCustodianApplicationStatus, dataCustodianBulkRequestURI, dataCustodianDefaultBatchResource, dataCustodianDefaultSubscriptionResource, dataCustodianId, dataCustodianResourceEndpoint, dataCustodianThirdPartySelectionScreenURI, grantTypes, logoUri, policyUri, redirectUri, registrationAccessToken, registrationClientUri, responseTypes, softwareId, softwareVersion, thirdPartyApplicationDescription, thirdPartyApplicationName, thirdPartyApplicationStatus, thirdPartyApplicationType, thirdPartyApplicationUse, thirdPartyDataCustodianSelectionScreenURI, thirdPartyLoginScreenURI, thirdPartyNotifyUri, thirdPartyPhone, thirdPartyScopeSelectionScreenURI, thirdPartyUserPortalScreenURI, tokenEndpointAuthMethod, tosUri, dataCustodianScopeSelectionScreenURI) 
VALUES (2,'THIRD_PARTY','GreenButtonData.org  ThirdParty Application','2014-01-02 05:00:00','/espi/1_1/resource/DataCustodian/ApplicationInformation/2','self','/espi/1_1/resource/DataCustodian/ApplicationInformation','up','2014-01-02 05:00:00','A0693ABF-67EA-4D5F-B584-36AD2902C85E','https://services.greenbuttondata.org/DataCustodian/oauth/authorize',NULL,'https://services.greenbuttondata.org/DataCustodian/oauth/token',NULL,'third_party',NULL,NULL,'secret',NULL,NULL,NULL,'1','',NULL,NULL,'data_custodian2','https://services.greenbuttondata.org/DataCustodian/espi/1_1/resource',NULL,'authorization_code,refresh_token',NULL,NULL,'https://services.greenbuttondata.org/ThirdParty/espi/1_1/OAuthCallBack',NULL,NULL,NULL,NULL,NULL,NULL,'Third Party (localhost)',NULL,NULL,NULL,NULL,NULL,'https://services.greenbuttondata.orgThirdParty/espi/1_1/Notification',NULL,'https://services.greenbuttondata.orgThirdParty/RetailCustomer/ScopeSelection',NULL,'client_secret_basic',NULL,'https://services.greenbuttondata.org/DataCustodian/RetailCustomer/ScopeSelectionList');


/* Add application_information_scopes */ 
INSERT INTO application_information_scopes (application_information_id, scope) VALUES (1, 'FB=4_5_15;IntervalDuration=3600;BlockDuration=monthly;HistoryLength=13');
INSERT INTO application_information_scopes (application_information_id, scope) VALUES (1, 'FB=4_5_15;IntervalDuration=900;BlockDuration=monthly;HistoryLength=13');
INSERT INTO application_information_scopes (application_information_id, scope) VALUES (2, 'FB=4_5_12_15_16;IntervalDuration=3600;BlockDuration=monthly;HistoryLength=13');

/* Add authorizations */ 
INSERT INTO authorizations (id, description, published, self_link_href, self_link_rel, up_link_href, up_link_rel, updated, uuid, access_token, authorization_uri, ap_duration, ap_start, code, error, errorDescription, errorUri, expiresIn, grantType, pp_duration, pp_start, refreshToken, resourceURI, responseType, scope, state, status, third_party, tokenType, application_information_id, retail_customer_id, subscription_id) 
VALUES (2,NULL,'2014-05-12 09:02:03',NULL,'self',NULL,'up','2014-05-12 09:02:03','0BA247E0-87F0-41E1-BB50-271468B00DC0','75dd9c46-becf-48b5-9cb5-9c3233d718d0','https://services.greenbuttondata.org/DataCustodian/espi/1_1/resource/Authorization/2',0,0,NULL,NULL,NULL,NULL,31536000,NULL,0,0,NULL,'https://services.greenbuttondata.org/DataCustodian/espi/1_1/resource/Batch/Bulk',NULL,'ThirdParty_Admin_Access',NULL,'1','third_party_admin',0,1,0,NULL);
INSERT INTO authorizations (id, description, published, self_link_href, self_link_rel, up_link_href, up_link_rel, updated, uuid, access_token, authorization_uri, ap_duration, ap_start, code, error, errorDescription, errorUri, expiresIn, grantType, pp_duration, pp_start, refreshToken, resourceURI, responseType, scope, state, status, third_party, tokenType, application_information_id, retail_customer_id, subscription_id) 
VALUES (4,NULL,'2014-05-12 09:02:03',NULL,'self',NULL,'up','2014-05-12 09:02:03','2BBCC436-E545-459F-90E9-99113C11FFD4','d89bb056-0f02-4d47-9fd2-ec6a19ba8d0c','https://services.greenbuttondata.org/DataCustodian/espi/1_1/resource/Authorization/4',0,0,NULL,NULL,NULL,NULL,31536000,NULL,0,0,NULL,'https://services.greenbuttondata.org/DataCustodian/espi/1_1/resource/ApplicationInformation/2',NULL,'ThirdParty_Registration_Access',NULL,'1','REGISTRATION_third_party',0,1,0,NULL);
