cp prepopulatesql_applicationinformation_dc_localhost8443.sql prepopulatesql_applicationinformation_dc.sql
cp prepopulatesql_tokenstore_localhost8443.sql prepopulatesql_tokenstore.sql
cp gbcmdcert.conf.sample gbcmdcert.conf
cp gbcmdcert_target.conf.sample gbcmdcert_target.conf
cp gbcmd.conf.sample gbcmd.conf
./initializedatabases.sh
