cp prepopulatesql_applicationinformation_dc_testthirdpartysecure.sql prepopulatesql_applicationinformation_dc.sql
cp prepopulatesql_tokenstore_testthirdpartysecure.sql prepopulatesql_tokenstore.sql
cp gbcmdcert_secure.conf gbcmdcert.conf
cp gbcmdcert_target_secure.conf gbcmdcert_target.conf
cp gbcmd_secure.conf gbcmd.conf
./initializedatabases.sh
