/*
 *
 *     Copyright (c) 2018-2025 Green Button Alliance, Inc.
 *
 *     Portions copyright (c) 2013-2018 EnergyOS.org
 *
 *     Licensed under the Apache License, Version 2.0 (the "License");
 *     you may not use this file except in compliance with the License.
 *     You may obtain a copy of the License at
 *
 *          http://www.apache.org/licenses/LICENSE-2.0
 *
 *     Unless required by applicable law or agreed to in writing, software
 *     distributed under the License is distributed on an "AS IS" BASIS,
 *     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *     See the License for the specific language governing permissions and
 *     limitations under the License.
 *
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilations of the source schema. 
// Generated on: 2013.08.27 at 01:43:57 PM EDT 
//


package org.greenbuttonalliance.espi.common.domain.legacy;

import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;
import jakarta.validation.constraints.NotNull;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import java.util.HashMap;
import java.util.Map;


/**
 * Category of service provided to the customer.
 * <p/>
 * <p>Java class for ServiceCategory complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="ServiceCategory">
 *   &lt;complexContent>
 *     &lt;extension base="{http://naesb.org/espi}Object">
 *       &lt;sequence>
 *         &lt;element name="kind" type="{http://naesb.org/espi}ServiceKind"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlRootElement(name = "ServiceCategory")
@XmlAccessorType(XmlAccessType.FIELD)
@Embeddable
//@Entity
//@Table(name = "service_categories")
public class ServiceCategory {
    public static final Long ELECTRICITY_SERVICE = 0L;
    public static final Long GAS_SERVICE = 1L;
    public static final Long WATER_SERVICE = 2L;
    public static final Long TIME_SERVICE = 3L;
    public static final Long HEAT_SERVICE = 4L;
    public static final Long REFUSE_WASTER_SERVICE = 5L;
    public static final Long SEWERAGE_SERVICE = 6L;
    public static final Long RATES_SERVICE = 7L;
    public static final Long TV_LICENSE_SERVICE = 8L;
    public static final Long INTERNET_SERVICE = 9L;

    private static final Map<Long, String> labels = new HashMap<>();

    static {
        labels.put(ELECTRICITY_SERVICE, "ELECTRICITY_SERVICE");
        labels.put(GAS_SERVICE, "GAS_SERVICE");
        labels.put(WATER_SERVICE, "WATER_SERVICE");
        labels.put(TIME_SERVICE, "TIME_SERVICE");
        labels.put(HEAT_SERVICE, "HEAT_SERVICE");
        labels.put(REFUSE_WASTER_SERVICE, "REFUSE_WASTER_SERVICE");
        labels.put(SEWERAGE_SERVICE, "SEWERAGE_SERVICE");
        labels.put(RATES_SERVICE, "RATES_SERVICE");
        labels.put(TV_LICENSE_SERVICE, "TV_LICENSE_SERVICE");
        labels.put(INTERNET_SERVICE, "INTERNET_SERVICE");
    }

    public ServiceCategory() {
    }

    public ServiceCategory(Long kind) {
        this.kind = kind;
    }

    @XmlElement(required = true)
    @NotNull
    @Column( name = "serviceCategory_kind")
//    @Id
    protected Long kind;

    /**
     * Gets the value of the kind property.
     *
     * @return possible object is
     *         {@link String }
     */
    public Long getKind() {
        return kind;
    }

    /**
     * Sets the value of the kind property.
     *
     * @param value allowed object is
     * {@link String }
     */
    public void setKind(Long value) {
        this.kind = value;
    }

    @Override
    public String toString() {
        return labels.get(kind);
    }
}
